### ISSUE TITLE
Atualizar valores de remuneração de CD, FG e FCC 2019

### ISSUE THREAD

**Issue by samirfor** [molx/unb#1]
Remuneração de CD, FG e FCC
Tabela de Remuneração dos Cargos de Direção das IFES (CD)

Lei nº 13.328/2016 de 29/07/2016 (link is external) -   Vigência a partir de 01/01/2019

Valores em Reais (R$)

CARGO	TOTAL	60%
CD-01	R$13.474,12	R$ 8.084,47
CD-02	R$ 11.263,53	R$ 6.758,12
CD-03	R$ 8.842,39	R$ 5.305,43
CD-04	R$ 6.421,26	R$ 3.852,76
Obs.: Os ocupantes de Cargo de Direção podem optar por receber o valor integral da remuneração do CD ou a remuneração do cargo acrescido de 60% da remuneração do CD.

 

Tabela de Remuneração das Funçoes Gratificadas (FG)

Lei nº 13.328/2016 de 29/07/2016 (link is external) -   Vigência a partir de 01/01/2019

Valores em Reais (R$)

NÍVEL	VENCIMENTO	GDAF¹	AGE²	TOTAL
FG-01	137,26	227,86	610,39	975,51
FG-02	117,24	194,62	344,42	656,28
FG-03	97,13	161,24	273,70	532,07
FG-04	66,39	110,20	94,24	270,83
FG-05	54,65	90,71	74,39	219,75
FG-06	40,48	67,19	53,47	161,14
FG-07	38,63	64,13	-	102,76
FG-08	28,58	47,44	-	76,02
FG-09	23,18	38,49	-	61,67
¹ Gratificação de Atividade pelo Desempenho de Função (art. 15 da Lei Delegada no 13, de 27 de agosto de 1992 (link is external)).
² Adicional de Gestão Educacional.

 

Remuneração das Funçoes de Coordenação de Curso (FCC)

Lei nº 13.328/2016 de 29/07/2016 (link is external) -   Vigência a partir de 01/01/2019

Valor em Reais (R$)

NÍVEL	VALOR
Único	R$ 983,18

**Comment by molx** [comment]
Esse repositório está desativado. O repositório atual da calculadora é outro, que já possui os valores atualizados, assim como outras modificações.

**Comment by samirfor** [comment]
> Esse repositório está desativado. O repositório atual da calculadora é outro, que já possui os valores atualizados, assim como outras modificações.

Pode disponibilizá-lo para a gente?
